In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\актив\appdata\local\programs\python\python314\lib\site-packages (3.0.0)
Requirement already satisfied: numpy>=2.3.3 in c:\users\актив\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\актив\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\актив\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\актив\appdata\local\programs\python\python314\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [4]:
# Task 3:
data = {
    'Name': ['Ali', 'Aruzhan', 'Dias', 'Amina', 'Nursultan'],
    'Age': [19, 21, 22, 20, 23],
    'Score': [85, 90, 78, 88, 92]
}

df = pd.DataFrame(data)
df

        Name  Age  Score
0        Ali   19     85
1    Aruzhan   21     90
2       Dias   22     78
3      Amina   20     88
4  Nursultan   23     92

In [5]:
# Task 4:

df.head(3)

df.describe()

df['Score'].mean()

np.float64(86.6)

In [6]:
# Task 5:


df[df['Age'] > 20]

df[df['Score'] > 80]

        Name  Age  Score
0        Ali   19     85
1    Aruzhan   21     90
3      Amina   20     88
4  Nursultan   23     92